targets:
  $default:
    builders:
      json_serializable|json_serializable:
        enabled: false
      mobx_json_serializable|json_serializable:
        enabled: true
        generate_for:
          include:
            - "test/integration/test_models.dart"

builders:
  json_serializable:
    target: ":json_serializable"
    import: "package:mobx_json_serializable/builder.dart"
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]