name: mobx_lint
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://mobx.dev
repository: https://github.com/mobxjs/mobx.dart
issue_tracker: https://github.com/mobxjs/mobx.dart/issues

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  analyzer: ">=6.0.0 <7.0.0"
  analyzer_plugin: ^0.11.2
  collection: ^1.16.0
  custom_lint_builder: ^0.5.2
  meta: ^1.7.0
  path: ^1.8.1
  mobx: ^2.2.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
