targets:
  $default:
    builders:
      json_serializable|json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/models/todo.dart
          exclude:
            - test/**
            - lib/**
            - example/**
      mobx_json_serializable:
        enabled: true
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/**
            - test/**
            - example/**
          exclude:
            - lib/models/todo.dart